### PR TITLE
Feature logo

### PR DESCRIPTION
**Pull request by zenangst**

### CODE REVIEW

**Comment by zenangst** [comment]
pages_logo

**Comment by vadymmarkov** [comment]
I like it for its simplicity. What do you think @hyperoslo/ios ?

**Comment by 3lvis** [comment]
Looks good :)

**Comment by RamonGilabert** [comment]
Looks great to me! :)

**Comment by jgorset** [comment]
I love it. So simple!

**Comment by attila-at-hyper** [comment]
Simple is beautiful. :) :+1:

**Pull request merged**
