### PR TITLE
upgrade to Swift 2.0

### LINKED ISSUE #27: Swift 2.0
Swift 2.0, must have :)
 Does anyone working on it?

### PR DESCRIPTION
**Pull request by kostiakoval**
Fix #27 
Giphy

### CODE REVIEW

**Comment by zenangst** [comment]
@kostiakoval 

687474703a2f2f6d65646961302e67697068792e636f6d2f6d656469612f67655977746f644239416949302f67697068792e676966

**Comment by cojoj** [comment]
@kostiakoval it looks like 6th β has brought new issues into this PR.

**Comment by kostiakoval** [comment]
@cojoj Thanks for bringing it! Swift changes so fast :)

**Comment by cojoj** [comment]
Yeah, I'm just wondering if it's good for us... 😂

**Comment by kostiakoval** [comment]
First year it was fun, now turns into pain :(

**Comment by richardtop** [comment]
In fact, right now using ObjC as dependencies is more stable than using Swift, even in Swift projects. You don't need to update them to 2.0 while Swift is still in very fast evolving stage.

**Comment by ded** [comment]
Heyo, XCode 7 finally left beta yesterday, so it seems today everyone is doing their official due diligence of upgrading their libraries. Any chance this can move forward?

**Comment by zenangst** [comment]
@ded :tada:

**Comment by ded** [comment]
:open_hands:

**Pull request merged**
